# Generated by Django 5.2.7 on 2025-11-18 22:23

import django.db.models.deletion
import usuarios_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre o Razón Social')),
                ('rut', models.CharField(blank=True, help_text='Formato: XX.XXX.XXX-X', max_length=15, null=True, unique=True, validators=[usuarios_app.validators.validar_rut_chileno], verbose_name='RUT')),
                ('codigo_cliente', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Código de Cliente')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, validators=[usuarios_app.validators.validar_telefono])),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('logo', models.ImageField(blank=True, help_text='Se usará en la cotización si está disponible.', null=True, upload_to='clientes_logos/', verbose_name='Logo de la Empresa (Opcional)')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PersonaContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('email', models.EmailField(max_length=100, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(max_length=20, validators=[usuarios_app.validators.validar_telefono], verbose_name='Número de Teléfono')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='usuarios_app.cliente', verbose_name='Empresa Asociada')),
            ],
            options={
                'verbose_name': 'Persona de Contacto',
                'verbose_name_plural': 'Personas de Contacto',
                'ordering': ['nombre'],
            },
        ),
    ]
