# Generated by Django 5.2.7 on 2025-12-09 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personacontacto',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contactos', to='usuarios_app.cliente', verbose_name='Empresa Asociada'),
        ),
    ]
