# Generated by Django 5.2.7 on 2025-11-06 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='rut',
            field=models.CharField(blank=True, help_text='Formato: XX.XXX.XXX-X', max_length=15, null=True, unique=True, verbose_name='RUT'),
        ),
    ]
