# Generated by Django 5.2.7 on 2025-12-09 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_app', '0002_protect_cascade_fix'),
    ]

    operations = [
        migrations.AddField(
            model_name='personacontacto',
            name='rol',
            field=models.CharField(default='Sin especificar', help_text='Ejemplo: Gerente de Compras, Ingeniero de Proyectos, etc.', max_length=100, verbose_name='Rol o Cargo'),
            preserve_default=False,
        ),
    ]
