# Generated by Django 5.2.7 on 2025-12-10 03:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('rut', models.CharField(blank=True, max_length=20)),
                ('empresa', models.CharField(blank=True, max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('proyecto_nombre', models.CharField(max_length=255, verbose_name='Nombre del Proyecto')),
                ('total_costo', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Costo Total General ($)')),
                ('notas_internas', models.TextField(blank=True, verbose_name='Notas Internas')),
                ('structural_items_json', models.JSONField(blank=True, null=True, verbose_name='JSON Ítems Estructurales')),
                ('overhead_items_json', models.JSONField(blank=True, null=True, verbose_name='JSON Ítems Adicionales')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones', to='cotizador_app.cliente', verbose_name='Cliente Asociado')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='CostoAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('unidad', models.CharField(default='Unidad', max_length=50)),
                ('cantidad', models.DecimalField(decimal_places=2, default=1.0, max_digits=8)),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costos_adicionales', to='cotizador_app.cotizacion')),
            ],
            options={
                'verbose_name': 'Costo Adicional',
                'verbose_name_plural': 'Costos Adicionales',
            },
        ),
        migrations.CreateModel(
            name='SeccionMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Ej: 'Baño 1', 'Estructura Techo', 'Habitación Principal'", max_length=200, verbose_name='Nombre de la Sección')),
                ('orden', models.IntegerField(default=0, help_text='Orden en que aparece la sección (menor = primero)', verbose_name='Orden de Visualización')),
                ('colapsada', models.BooleanField(default=False, verbose_name='Colapsada')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='cotizador_app.cotizacion', verbose_name='Cotización')),
            ],
            options={
                'verbose_name': 'Sección de Materiales',
                'verbose_name_plural': 'Secciones de Materiales',
                'ordering': ['orden', 'id'],
                'unique_together': {('cotizacion', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='MaterialEstructural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='ID Perfil API')),
                ('material_nombre', models.CharField(max_length=300, verbose_name='Material')),
                ('largo_m', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Largo (m)')),
                ('unidad_comercial', models.DecimalField(decimal_places=2, default=0.0, help_text='Largo requerido / 6 metros por barra', max_digits=8, verbose_name='U. Comercial')),
                ('cant_necesaria', models.IntegerField(default=1, help_text='Unidad comercial redondeada hacia arriba', verbose_name='C. Necesaria')),
                ('cant_a_comprar', models.IntegerField(default=1, help_text='Cantidad necesaria × 1.25 (redondeado arriba)', verbose_name='A Comprar')),
                ('peso_kg_m', models.DecimalField(decimal_places=3, default=0.0, max_digits=8, verbose_name='Peso (kg/m)')),
                ('valor_unitario_m', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Unit. ($/m)')),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales_estructurales', to='cotizador_app.cotizacion', verbose_name='Cotización')),
                ('seccion', models.ForeignKey(blank=True, help_text='Sección a la que pertenece este material (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiales', to='cotizador_app.seccionmaterial', verbose_name='Sección')),
            ],
            options={
                'verbose_name': 'Material Estructural',
                'verbose_name_plural': 'Materiales Estructurales',
                'ordering': ['seccion__orden', 'id'],
            },
        ),
    ]
