# Generated by Django 5.2.7 on 2025-11-18 22:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('proyecto_nombre', models.CharField(max_length=255, verbose_name='Nombre del Proyecto')),
                ('total_costo', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Costo Total General ($)')),
                ('notas_internas', models.TextField(blank=True, verbose_name='Notas Internas')),
                ('structural_items_json', models.JSONField(blank=True, null=True, verbose_name='JSON Ítems Estructurales')),
                ('overhead_items_json', models.JSONField(blank=True, null=True, verbose_name='JSON Ítems Adicionales')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones', to='usuarios_app.cliente', verbose_name='Cliente Asociado')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='CostoAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('unidad', models.CharField(default='Unidad', max_length=50)),
                ('cantidad', models.DecimalField(decimal_places=2, default=1.0, max_digits=8)),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costos_adicionales', to='cotizador_app.cotizacion')),
            ],
            options={
                'verbose_name': 'Costo Adicional',
                'verbose_name_plural': 'Costos Adicionales',
            },
        ),
        migrations.CreateModel(
            name='MaterialEstructural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_nombre', models.CharField(max_length=150)),
                ('largo_mm', models.IntegerField(default=0)),
                ('largo_m', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('unidad_comercial', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('cant_necesaria', models.IntegerField(default=1)),
                ('cant_a_comprar', models.IntegerField(default=1)),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('peso_kg_m', models.DecimalField(decimal_places=3, default=0.0, max_digits=8)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales_estructurales', to='cotizador_app.cotizacion')),
            ],
            options={
                'verbose_name': 'Material Estructural',
                'verbose_name_plural': 'Materiales Estructurales',
            },
        ),
    ]
