# Generated by Django 5.2.7 on 2025-12-05 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialestructural',
            options={'ordering': ['seccion__orden', 'id'], 'verbose_name': 'Material Estructural', 'verbose_name_plural': 'Materiales Estructurales'},
        ),
        migrations.RemoveField(
            model_name='materialestructural',
            name='largo_mm',
        ),
        migrations.RemoveField(
            model_name='materialestructural',
            name='valor_unitario',
        ),
        migrations.AddField(
            model_name='materialestructural',
            name='profile_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID Perfil API'),
        ),
        migrations.AddField(
            model_name='materialestructural',
            name='valor_unitario_m',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Unit. ($/m)'),
        ),
        migrations.AlterField(
            model_name='materialestructural',
            name='cant_a_comprar',
            field=models.IntegerField(default=1, help_text='Cantidad necesaria × 1.25 (redondeado arriba)', verbose_name='A Comprar'),
        ),
        migrations.AlterField(
            model_name='materialestructural',
            name='cant_necesaria',
            field=models.IntegerField(default=1, help_text='Unidad comercial redondeada hacia arriba', verbose_name='C. Necesaria'),
        ),
        migrations.AlterField(
            model_name='materialestructural',
            name='cotizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales_estructurales', to='cotizador_app.cotizacion', verbose_name='Cotización'),
        ),
        migrations.AlterField(
            model_name='materialestructural',
            name='largo_m',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Largo (m)'),
        ),
        migrations.AlterField(
            model_name='materialestructural',
            name='material_nombre',
            field=models.CharField(max_length=150, verbose_name='Material'),
        ),
        migrations.AlterField(
            model_name='materialestructural',
            name='peso_kg_m',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=8, verbose_name='Peso (kg/m)'),
        ),
        migrations.AlterField(
            model_name='materialestructural',
            name='unidad_comercial',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Largo requerido / 6 metros por barra', max_digits=8, verbose_name='U. Comercial'),
        ),
        migrations.CreateModel(
            name='SeccionMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Ej: 'Baño 1', 'Estructura Techo', 'Habitación Principal'", max_length=200, verbose_name='Nombre de la Sección')),
                ('orden', models.IntegerField(default=0, help_text='Orden en que aparece la sección (menor = primero)', verbose_name='Orden de Visualización')),
                ('colapsada', models.BooleanField(default=False, verbose_name='Colapsada')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='cotizador_app.cotizacion', verbose_name='Cotización')),
            ],
            options={
                'verbose_name': 'Sección de Materiales',
                'verbose_name_plural': 'Secciones de Materiales',
                'ordering': ['orden', 'id'],
                'unique_together': {('cotizacion', 'nombre')},
            },
        ),
        migrations.AddField(
            model_name='materialestructural',
            name='seccion',
            field=models.ForeignKey(blank=True, help_text='Sección a la que pertenece este material (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiales', to='cotizador_app.seccionmaterial', verbose_name='Sección'),
        ),
    ]
