# Generated by Django 5.2.7 on 2025-12-09 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador_app', '0002_alter_materialestructural_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costoadicional',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='materialestructural',
            name='material_nombre',
            field=models.CharField(max_length=300, verbose_name='Material'),
        ),
        migrations.AlterField(
            model_name='materialestructural',
            name='profile_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='ID Perfil API'),
        ),
    ]
