"""
Django settings for core_config project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
TEMPLATES_DIR = os.path.join(BASE_DIR, "templates")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+26ncw7f97=%$d*=akh8%f(6%-=+p9q4+j$k0vw4ko09b!$8#%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# SE MODIFICO PARA EL RAILWAY
ALLOWED_HOSTS = ["*"]

# ✅ Django Debug Toolbar - IPs permitidas para ver la toolbar
INTERNAL_IPS = [
    '127.0.0.1',
    'localhost',
]


LOGIN_URL = '/' # Redirige a la página de login si no está autenticado
LOGIN_REDIRECT_URL = '/home/' # Redirige a esta página después de iniciar sesión
LOGOUT_REDIRECT_URL = '/' # Redirige a esta página después de cerrar sesión

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'debug_toolbar',  # ✅ Django Debug Toolbar (solo desarrollo)
    'widget_tweaks',
    'django_vite',
    'rest_framework',
    'main_app',
    'usuarios_app',
    'cotizador_app',
    'profiles_api',
    'login_app',
    'corsheaders', # RAILWAY
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', # RAILWAY
    'django.middleware.common.CommonMiddleware', #RAILWAY
    'debug_toolbar.middleware.DebugToolbarMiddleware',  # ✅ Debug Toolbar (debe estar temprano)
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core_config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATES_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core_config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'assets/django-assets',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_ROOT = BASE_DIR / 'media'
# La URL base para acceder a esos archivos subidos
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuración de Vite
DJANGO_VITE = {
    "default": {
        "dev_mode": False,
        "manifest_path": BASE_DIR / "assets/django-assets/manifest.json", # Forzamos la ruta exacta
        "static_url_prefix": "", # <--- ESTO ES LA CLAVE (Déjalo vacío)
    }
}

CORS_ALLOW_ALL_ORIGINS = True # RAILWAY

CSRF_TRUSTED_ORIGINS = [
    'https://cotizador.up.railway.app',
]